nodeFilterType: 1
nodes: ["/node_monitors","/rosout","/system_monitors","/amcl","/robot_pose_publisher"]
maxPermissibleCpuUsage: 3.0
maxPermissibleMemoryUsage: 3.0
timerUpdateFrequency : 1.0
maxPermissibleNodeRestart : 5

restart_path: "/home/addverb/ADDVERB/Session/VSCODE/Demo/catkin_ws/node_stat"
