bagDirectory : /home/ra-1/catkin_ws/src/Robot-Diagnostics/robot_diagnostics/bags/
splitTime : 1  # minutes
oldFileDeletionTime: 5 #minutes
maxBagSize: 4.0 #MB
maxSplit: 5     # Numbers
maxFolderSize: 20.0 #MB > maxBagSize*maxSplit

bag_topics : ["/scan","/particlecloud"]
##Deletion of bag file criteria

#a)Either when the files last updated time gets passed 'oldFileDeletionTime' minutes OR
#b)Folder with bags stored gets exhausted with size greater than 'maxFolderSize' MB  OR
#c)Maximum number of split files in the folder gets greater than  'maxSplit' numbers
