frequency: 1.0
filter_type: 2
topics: ["/node_monitors","/rosout"]
cpu_threshold: 3.0
memory_threshold: 3.0
error_threshold: 2.0
publish_ping_rate: false
number_of_restart: 10
restart_path: "/home/addverb/ADDVERB/Session/VSCODE/Demo/catkin_ws/node_stat"
