minAcceptableFrequencyFactor : 0.9  # by what factor it's permissible to drop topic frequency.Varies from 0.1 to 1.0
topics: 
  - name: /robot_pose
    frequency: 10.0
  - name: /odom
    frequency: 12.0
  - name: /odoms
    frequency: 12.0
